#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# EtudePlus - Free Deployment Script
# This script helps deploy EtudePlus to various free hosting platforms
# ═══════════════════════════════════════════════════════════════════════════════

set -e

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║        EtudePlus - Free Deployment Configuration                ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Choose your deployment platform:"
echo ""
echo "  1) Render.com        (Recommended - Easiest, 750h/month free)"
echo "  2) Railway.app       (Good alternative, $5 credit/month)"
echo "  3) Fly.io            (Great for global deployment)"
echo "  4) Vercel + Supabase (Frontend + Managed DB)"
echo "  5) Oracle Cloud      (Always free tier, more setup)"
echo "  6) Show all instructions"
echo ""
read -p "Enter your choice [1-6]: " choice

case $choice in
    1) deploy_render ;;
    2) deploy_railway ;;
    3) deploy_fly ;;
    4) deploy_vercel ;;
    5) deploy_oracle ;;
    6) show_all ;;
    *) echo "Invalid choice"; exit 1 ;;
esac

# ═══════════════════════════════════════════════════════════════════════════════
deploy_render() {
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "  RENDER.COM DEPLOYMENT (Recommended)"
    echo "════════════════════════════════════════════════════════════════════"
    echo ""
    echo "📋 Prerequisites:"
    echo "   • GitHub account (to connect your repo)"
    echo "   • Render account (free at render.com)"
    echo ""
    echo "🚀 Step-by-Step Deployment:"
    echo ""
    echo "1. Push your code to GitHub:"
    echo "   git add ."
    echo "   git commit -m 'Prepare for deployment'"
    echo "   git push origin main"
    echo ""
    echo "2. Go to https://dashboard.render.com and click 'New +'"
    echo ""
    echo "3. Create PostgreSQL Database:"
    echo "   • Select 'PostgreSQL'"
    echo "   • Name: etudeplus-db"
    echo "   • Region: Frankfurt (or closest)"
    echo "   • Plan: Free"
    echo "   • Click 'Create Database'"
    echo ""
    echo "4. Create Redis Instance:"
    echo "   • Select 'Redis'"
    echo "   • Name: etudeplus-redis"
    echo "   • Plan: Free"
    echo "   • Click 'Create Redis Instance'"
    echo ""
    echo "5. Create Backend Web Service:"
    echo "   • Select 'Web Service'"
    echo "   • Connect your GitHub repo"
    echo "   • Name: etudeplus-api"
    echo "   • Region: Same as database"
    echo "   • Branch: main"
    echo "   • Root Directory: backend"
    echo "   • Runtime: Docker"
    echo "   • Dockerfile Path: ./Dockerfile.backend"
    echo "   • Plan: Free"
    echo ""
    echo "6. Set Environment Variables (click 'Advanced'):"
    echo "   • DATABASE_URL: \${etudeplus-db.DATABASE_URL}"
    echo "   • REDIS_URL: \${etudeplus-redis.DATABASE_URL}"
    echo "   • SECRET_KEY: (generate with: openssl rand -hex 32)"
    echo "   • DEBUG: False"
    echo "   • KEYCLOAK_URL: https://your-keycloak.com"
    echo "   • KEYCLOAK_REALM: schoolflow"
    echo "   • KEYCLOAK_CLIENT_ID: schoolflow-backend"
    echo "   • KEYCLOAK_CLIENT_SECRET: your-secret"
    echo ""
    echo "7. Create Frontend Static Site:"
    echo "   • Select 'Static Site'"
    echo "   • Connect same GitHub repo"
    echo "   • Name: etudeplus-frontend"
    echo "   • Root Directory: ./"
    echo "   • Build Command: npm install && npm run build"
    echo "   • Publish Directory: dist"
    echo "   • Set VITE_API_URL: https://etudeplus-api.onrender.com/api/v1"
    echo ""
    echo "✅ Your app will be available at:"
    echo "   • Frontend: https://etudeplus-frontend.onrender.com"
    echo "   • Backend API: https://etudeplus-api.onrender.com"
    echo ""
    echo "💡 Tips:"
    echo "   • Free tier spins down after inactivity (30s cold start)"
    echo "   • Use a Uptime monitor to keep it alive"
    echo "   • For Keycloak, use a separate service or Render's Docker"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════════
deploy_railway() {
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "  RAILWAY.APP DEPLOYMENT"
    echo "════════════════════════════════════════════════════════════════════"
    echo ""
    echo "📋 Prerequisites:"
    echo "   • GitHub account"
    echo "   • Railway account (free $5 credit/month)"
    echo ""
    echo "🚀 Step-by-Step Deployment:"
    echo ""
    echo "1. Install Railway CLI:"
    echo "   npm i -g @railway/cli"
    echo ""
    echo "2. Login to Railway:"
    echo "   railway login"
    echo ""
    echo "3. Initialize project:"
    echo "   railway init"
    echo ""
    echo "4. Add PostgreSQL:"
    echo "   railway add --database postgres"
    echo ""
    echo "5. Add Redis:"
    echo "   railway add --database redis"
    echo ""
    echo "6. Deploy backend:"
    echo "   railway up --dockerfile Dockerfile.backend"
    echo ""
    echo "7. Set environment variables:"
    echo "   railway variables set DATABASE_URL=\${{Postgres.DATABASE_URL}}"
    echo "   railway variables set REDIS_URL=\${{Redis.REDIS_URL}}"
    echo "   railway variables set SECRET_KEY=\$(openssl rand -hex 32)"
    echo "   railway variables set DEBUG=False"
    echo ""
    echo "8. Generate domain:"
    echo "   railway domain"
    echo ""
    echo "✅ Your app will be available at the generated domain"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════════
deploy_fly() {
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "  FLY.IO DEPLOYMENT"
    echo "════════════════════════════════════════════════════════════════════"
    echo ""
    echo "📋 Prerequisites:"
    echo "   • Fly.io account (free tier: 3 VMs, 3GB volume)"
    echo "   • flyctl CLI installed"
    echo ""
    echo "🚀 Step-by-Step Deployment:"
    echo ""
    echo "1. Install flyctl:"
    echo "   curl -L https://fly.io/install.sh | sh"
    echo ""
    echo "2. Login:"
    echo "   fly auth login"
    echo ""
    echo "3. Create app:"
    echo "   fly apps create etudeplus-api"
    echo ""
    echo "4. Create PostgreSQL (managed):"
    echo "   fly postgres create"
    echo "   # Choose development (free) or HA"
    echo ""
    echo "5. Attach database:"
    echo "   fly postgres attach etudeplus-db"
    echo ""
    echo "6. Set secrets:"
    echo "   fly secrets set SECRET_KEY=\$(openssl rand -hex 32)"
    echo "   fly secrets set DEBUG=False"
    echo "   fly secrets set KEYCLOAK_URL=https://your-keycloak.com"
    echo ""
    echo "7. Deploy:"
    echo "   fly deploy"
    echo ""
    echo "8. Scale (free tier limits):"
    echo "   fly scale vm shared-cpu-1x --memory 256"
    echo "   fly scale count 1"
    echo ""
    echo "✅ Your app will be available at:"
    echo "   https://etudeplus-api.fly.dev"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════════
deploy_vercel() {
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "  VERCEL + SUPABASE DEPLOYMENT"
    echo "════════════════════════════════════════════════════════════════════"
    echo ""
    echo "📋 This approach uses:"
    echo "   • Vercel for Frontend (Free tier)"
    echo "   • Supabase for Backend + Database (Free tier)"
    echo ""
    echo "🚀 Step-by-Step Deployment:"
    echo ""
    echo "=== SUPABASE SETUP ==="
    echo ""
    echo "1. Go to https://supabase.com and create a project"
    echo ""
    echo "2. Get your credentials from Project Settings > API:"
    echo "   • Project URL"
    echo "   • Anon Key"
    echo "   • Service Role Key"
    echo ""
    echo "3. Run migrations in SQL Editor:"
    echo "   Copy content from: backend/alembic/versions/"
    echo ""
    echo "=== VERCEL FRONTEND ==="
    echo ""
    echo "4. Install Vercel CLI:"
    echo "   npm i -g vercel"
    echo ""
    echo "5. Deploy:"
    echo "   vercel --prod"
    echo ""
    echo "6. Set environment variables in Vercel dashboard:"
    echo "   • VITE_SUPABASE_URL=https://xxx.supabase.co"
    echo "   • VITE_SUPABASE_ANON_KEY=your-key"
    echo ""
    echo "✅ Your app will be available at your Vercel domain"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════════
deploy_oracle() {
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "  ORACLE CLOUD ALWAYS FREE TIER"
    echo "════════════════════════════════════════════════════════════════════"
    echo ""
    echo "📋 Free Resources:"
    echo "   • 2 AMD Compute VMs (1/8 OCPU, 1GB RAM each)"
    echo "   • 4 Arm Compute VMs (24GB RAM total)"
    echo "   • 2 Block Volumes (200GB total)"
    echo "   • 10TB/month outbound data"
    echo ""
    echo "🚀 Step-by-Step Deployment:"
    echo ""
    echo "1. Create Oracle Cloud account (requires credit card for verification)"
    echo ""
    echo "2. Create a VM Instance:"
    echo "   • Shape: VM.Standard.E2.1.Micro (Free tier)"
    echo "   • OS: Ubuntu 22.04"
    echo "   • Add SSH key"
    echo ""
    echo "3. SSH into your VM:"
    echo "   ssh ubuntu@<public-ip>"
    echo ""
    echo "4. Install Docker:"
    echo "   curl -fsSL https://get.docker.com | sh"
    echo "   sudo usermod -aG docker ubuntu"
    echo ""
    echo "5. Install Docker Compose:"
    echo "   sudo apt install docker-compose-plugin"
    echo ""
    echo "6. Clone and deploy:"
    echo "   git clone <your-repo>"
    echo "   cd etudeplus"
    echo "   cp .env.example .env"
    echo "   # Edit .env with your settings"
    echo "   docker compose up -d"
    echo ""
    echo "7. Open ports in Oracle Security List:"
    echo "   • 80 (HTTP)"
    echo "   • 443 (HTTPS)"
    echo "   • 8000 (API)"
    echo ""
    echo "8. Configure firewall:"
    echo "   sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT"
    echo "   sudo iptables -I INPUT -p tcp --dport 443 -j ACCEPT"
    echo "   sudo netfilter-persistent save"
    echo ""
    echo "✅ Your app will be available at the public IP"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════════
show_all() {
    deploy_render
    echo ""
    echo "Press Enter to continue to Railway..."
    read
    deploy_railway
    echo ""
    echo "Press Enter to continue to Fly.io..."
    read
    deploy_fly
    echo ""
    echo "Press Enter to continue to Vercel..."
    read
    deploy_vercel
    echo ""
    echo "Press Enter to continue to Oracle Cloud..."
    read
    deploy_oracle
}

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  📚 For more details, see DEPLOYMENT_GUIDE.md"
echo "════════════════════════════════════════════════════════════════════"
